import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Box } from '@mui/material';
import styles from '../styles/Home.module.css';
import TopBar from '../components/TopBar';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Box sx={{ display: 'flex', height: "100vh" }}>
                    <TopBar></TopBar>
                </Box>
            </main>

            <footer className={styles.footer}>
            </footer>
        </div>
    )
}
